security:
    encoders:
        Kutny\User\User:
            algorithm:  bcrypt
            iterations: %bcrypt_iterations%

        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        admin:
            entity: { class: Kutny\User\User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_area:
            request_matcher: security.request_matcher
            pattern:  ^/
            anonymous: ~
            form_login:
                check_path: route.login_check
                login_path: route.login
                default_target_path: route.dashboard
                use_referer: true

            logout:
                path: route.logout
                target: route.login

            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~

    access_control:
        - { host: %hostname%, path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { host: %hostname%, path: ^/registration, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { host: api.%hostname%, path: ^/, roles: ROLE_USER }
        - { host: %hostname%, path: ^/, roles: ROLE_USER }
